### ISSUE TITLE
Default Bedrock UDP port is not being set as expected (Ruby)

### ISSUE THREAD

**Issue by ldilley** [FragLand/minestat#100]
### Expected Behavior
* When port number and request type are not specified, the default Bedrock UDP port should be set to `19132` after all other SLP queries fail.

### Actual Behavior/Symptoms
* The branch to change the port is never executed.

### How to Reproduce Behavior/Symptoms
* Attempt to query a Bedrock/PE server without specifying the port or request type.

### MineStat Version
* 2.2.0

### Programming Language and Compiler/Interpreter Version
* Affects all applicable Ruby versions

### Operating System
* Affects all

### Output/Screenshot(s)
N/A

**Comment by mindsolve** [comment]
Do we have other implementations where the port is optional? Or just the Ruby one?

**Comment by ldilley** [comment]
Aside from Ruby, the Java, PHP, and PowerShell implementations allow for an optional port number.

**Comment by mindsolve** [comment]
Thanks. Let's keep this in mind when incorporating the Bedrock protocol for those implementations :)

**Comment by ldilley** [comment]
My original thinking was to enable users to conveniently specify just an address to check. With the recent inclusion of Bedrock support, I've written the PHP and Ruby implementations to attempt the use of all SLP protocols prior to trying the default Bedrock port. The aforementioned behavior only occurs when an address alone is specified (no specific port number or request type given as arguments).
