### ISSUE TITLE
Bedrock support broken

### ISSUE THREAD

**Issue by Pronner** [FragLand/minestat#112]
I've seen the Bedrock Support feature request and in the end of the issue bedrock support was added, however it still doesn't work.
### Expected Behavior
```cs
MineStat ms = new MineStat("notexmc.net", 19132);
			if (ms.ServerUp)
			{

				txtNotexPlayers.Text = $@"{ms.CurrentPlayers}/{ms.MaximumPlayers} Players";
				txtNotexMOTD.Text = $@"{ms.Motd}";

			}
			else
            {

				MessageBox.Show("a");

            }
```

Supposed to show PlayerCount + MOTD

### Actual Behavior/Symptoms
* It goes with the else statement and doesn't work EVEN THO MY SERVER IS ONLINE AND HAS PLAYERS...

### How to Reproduce Behavior/Symptoms
* already wrote code on top

### MineStat Version
* 2.1.1 from NuGet

### Programming Language and Compiler/Interpreter Version
* C#

### Operating System
* Windows

### Output/Screenshot(s)
![image](https://user-images.githubusercontent.com/84229419/184507964-637342b8-4b81-4748-b7a1-2e19ef1ec28f.png)

**Comment by Pronner** [comment]
I don't think the package even works in general
Tried to ping play.pvplegacy.net with port 25565 and even that didn't work

**Comment by ldilley** [comment]
Have you tried the latest version from master, 3.0.1?

**Comment by mindsolve** [comment]
Hi @Pronner,
welcome to MineStat and thanks for your bug report :)

Regarding the C# version of MineStat and Bedrock/RakNet:
This has been implemented in PR #105 (version 3.0.1) - that version has not yet been uploaded to NuGet. As such, you currently can't use Bedrock with C#, if you are using the NuGet version.
@ldilley: Could you please upload the latest version to NuGet? Thank you!

Regarding your second point:
In my testing the mentioned server works, only the MOTD is empty.
The new C# version also contains some bugfixes regarding MOTDs, with the new version (3.0.1) that also works.

**Comment by ldilley** [comment]
@mindsolve: Do you have visibility and permission to [manually run the NuGet publish action](https://github.com/FragLand/minestat/actions/workflows/nuget-publish.yml)?

**Comment by ldilley** [comment]
@Pronner: The NuGet package has been updated to version 3.0.1. You should be good to go after you update.

**Comment by Pronner** [comment]
Thank you, I will test it.

**Comment by Pronner** [comment]
It works very well now, Thank you!
