### ISSUE TITLE
Favicon Support

### ISSUE THREAD

**Issue by Jordan9232** [FragLand/minestat#120]
### Feature Description
* The current version of Java (and I think Bedrock too) return a "favicon" base64 string field in the response that this library is not capturing. It would be nice to be able to access this. For the earlier protocols that don't support it this new property would be null.

**Comment by ldilley** [comment]
### Progress

| Variant | Favicon Support |
| --- | --- |
| C# | :x: |
| Go | :x: |
| Java | :heavy_check_mark: (Merged PR FragLand/minestat#121) |
| JavaScript | :x: |
| PHP | :x: |
| Perl | :x: |
| PowerShell | :x: |
| Python | :x: |
| Ruby | :heavy_check_mark: (Merged PR FragLand/minestat#121) |

**Comment by Ajoro** [comment]
Powershell already supports base64 string
![image](https://user-images.githubusercontent.com/21109286/207144146-99c85b79-67ce-49a6-a13c-eeee0230a343.png)

**Comment by ldilley** [comment]
Resolving this issue... When the Go, JavaScript, and Perl subprojects get caught up, they will have this feature as well (these currently lack SLP 1.7+ support).
