### ISSUE TITLE
Feature Request - Net Core Support

### ISSUE THREAD

**Issue by jrdiver** [FragLand/minestat#123]
### Feature Description
*
If you change the C# library's target from Framework 4.6 to NetStandard2.0, it would allow it to be used with framework and net core projects.

**Comment by mindsolve** [comment]
Hi @jrdiver, a warm welcome to MineStat!

We have in the past already discussed changing the target framework - we also discovered that we can also dual-target `net46` and .net standard 2.0 (which equals to 4.6.1 with some extra footnotes) with the TargetFramework**s** directive and some other smaller changes to the rest of the csproj file. This would allow us to keep compatibility with .NET Framework 4.6(.0).

As far as I can remember, there are no specific reasons why this hasn't happened yet, just that nobody has yet done it 😄
We would greatly appreciate a PR for that :)

**Comment by jrdiver** [comment]
Submitted a pull request as #124

**Comment by ldilley** [comment]
Thank you for your contribution, @jrdiver, and for the review, @mindsolve. I am closing this issue since PR #124 has been merged.
