### ISSUE TITLE
Minestat Java reports servers as always offline (MC 1.19.2 / Java 17)

### ISSUE THREAD

**Issue by mindsolve** [FragLand/minestat#129]
Thank you for quicky reply, I'm using java 17.
The snippet of code that always reports that server is down:

```
log.info("Checking server status: {}:{}", ip, MINECRAFT_PORT);
MineStat mineStat = new MineStat(ip, MINECRAFT_PORT);

int players;
if(mineStat.isServerUp()) {
	log.info("Server {} {} is up", instance.getName(), ip);
	players = mineStat.getCurrentPlayers();
} else {
	log.info("Server {} {} is down", instance.getName(), ip);
	players = 0;
}

log.info("Players online: {}", players);
```

_Originally posted by @lUNuXl in https://github.com/FragLand/minestat/issues/21#issuecomment-1345166505_

**Comment by mindsolve** [comment]
Hi @lUNuXl and @ldilley,

I have gone ahead and moved this to a new issue.

@lUNuXl:
- Are you sure that you can reach the minecraft server from where you are running this code? And that `ip` and `MINECRAFT_PORT` are correct?
- What version of MineStat Java are you using and from where (Maven?)?
- Could you try to run [the example java code](https://github.com/FragLand/minestat/blob/master/Java/Example.java) with your server and report its output?


With the following test code, I was able to successfully check the status of a Paper 1.19.2 server:

```java
public static void main(String[] args) {
	String ip = "gameserv.ng.fx3.eu";
	int MINECRAFT_PORT = 25565;

	MineStat mineStat = new MineStat(ip, MINECRAFT_PORT);
	int players;
	if(mineStat.isServerUp()) {
		System.out.printf("Server %s %s is up%n", "examplename", ip);
		players = mineStat.getCurrentPlayers();
	} else {
		System.out.printf("Server %s %s is down%n", "examplename", ip);
		players = 0;
	}

	System.out.printf("Players online: %d%n", players);
}
```
Output:
```
Server examplename gameserv.ng.fx3.eu is up
Players online: 0
```

Best regards,
MindSolve

**Comment by lUNuXl** [comment]
@mindsolve @ldilley I've created a minimal gradle project for reproducting this issue:

https://github.com/lUNuXl/minestat_issue

When run I get the following output:
```
12:59:19.760 [main] INFO org.example.Main - Checking server status: 35.210.62.232:25565
12:59:20.116 [main] INFO org.example.Main - Server 35.210.62.232 is down
12:59:20.116 [main] INFO org.example.Main - Players online: 0
```

**Comment by lUNuXl** [comment]
Hm, I think I now know what the issue is.

Calling:

```mineStat.isServerUp()```

returns always false

**Comment by ldilley** [comment]
Is your server up now, @lUNuXl? I attempted to `telnet` to TCP port `25565` of `35.210.62.232` and the connection times out. Perhaps traffic is only allowed from certain source addresses or the server isn't really up?

```
telnet 35.210.62.232 25565
Trying 35.210.62.232...
telnet: connect to address 35.210.62.232: Operation timed out
telnet: Unable to connect to remote host
```

**Comment by GenifeG** [comment]
Same on python (i can't get info of localhost server)

**Comment by ldilley** [comment]
@GenifeG: What are the versions of the Python module and Minecraft server you're using? Are you absolutely certain that the server is listening and accepting connections on the loopback interface? If the connection is refused or it times out (as shown in my previous comment above yours using `telnet`) to 127.0.0.1:25565, then it is rightfully detected as being offline.

**Comment by ldilley** [comment]
@GenifeG: Your issue should be resolved (see #133/#134 for details). @mindsolve found an error with the connection status check in the Python module. Version `2.3.1` contains the fix and this was also deployed to PyPI.

**Comment by Enderman-Teleporting** [comment]
Hi I am also using java and I find servers with `online-mode` set as `true`(such as 2b2t.org and mc.hypixel.net) can never be recognized as online

**Comment by ldilley** [comment]
Thank you for the additional information, @Enderman-Teleporting. I can confirm the same behavior while probing certain servers. I've narrowed the cause down to how exceptions are handled in Java. `java.io.EOFException` is being thrown which causes the connection status to be set to `CONNFAIL`. This prevents the JSON query from being executed. The return value should really be `UNKNOWN` in this context. I'll submit a fix soon and reply here when complete.

Stack trace:
```
java.io.EOFException
        at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295)
        at me.dilley.MineStat.legacyRequest(MineStat.java:472)
        at me.dilley.MineStat.<init>(MineStat.java:237)
        at me.dilley.MineStat.<init>(MineStat.java:183)
        at Example.main(Example.java:8)
```

Problematic code:
```java
catch(IOException ioe)
{
  return ConnectionStatus.CONNFAIL;
}
```

**Comment by ldilley** [comment]
This issue should be resolved as of PR #135's merger (title says Python, but it also includes the Java fix). The Maven package was also uploaded as version `3.0.5` and should be synchronized within a couple of hours.

**Comment by Enderman-Teleporting** [comment]
Thanks for your attention to the problem and it is now OKAY with the latest version😀

**Comment by ldilley** [comment]
You are welcome. I am glad that the latest commit resolved your issue. You should be all set too, @lUNuXl.
