### ISSUE TITLE
[Javascript] minestat.online returns True even after server is shut down

### ISSUE THREAD

**Issue by Conanap** [FragLand/minestat#130]
Hello! I have a web server running that displays the status of my minecraft server. Here's the relevant code:
```
const mcstatus = require('minestat');
...
app.get('/statuses/mc', function(req, res, next) {
    return mcstatus.init('localhost', 25565, function(result) {
        return res.json(mcstatus.online ? "Online" : "Offline");
    });
});
```

Minecraft server is hosted on `localhost` on `25565`, launched via a batch script:
```
java -Xmx4096M -Xms4096M -jar server.jar -nogui
pause
```

When the web server is initialised, and the minecraft server is not, it behaves as expected, reporting that the server is offline. Once I initialise the minecraft server, it also correctly reports ther server is now online. However, once I terminate the bashscript with `ctrl+c`, and `Y` to the confirmation dialogue, the status seems to be stuck as online.

I've checked via the minecraft client, and the server is indeed offline.

Let me know if there's any other information I can provide, thanks!

**Comment by Conanap** [comment]
Hey, thanks for the quick reply! I've refreshed the broswer as well and clear cache, but couldn't seem to get it to show as offline. The site makes a request for the updated status to the server every 10 seconds, and in the networking tab I can see that the response is "online" as well

![image](https://user-images.githubusercontent.com/15721264/207285022-df984ec0-1552-4771-a42e-40afbbcb5f6b.png)

Perhaps the server version may be the issue? Is there support for 1.19.x? Thanks!

**Comment by ldilley** [comment]
After some discussion and testing with @mindsolve, it turns out that this is a bug if the interpreter is run interactively/persistently. The interpreter retains the `true` until it exits (or the variable is explicitly reset). We have a small fix that I'll be pushing soon.

**Comment by ldilley** [comment]
PR #131 has been submitted as a fix. Please let us know if that resolves your issue, @Conanap. If so, I'll ensure that the npm package gets updated as well.

**Comment by Conanap** [comment]
Thanks @ldilley! The fix works perfectly. Please give me aheads up if possible when it gets deployed to npm. Many thanks for the prompt fix!

**Comment by ldilley** [comment]
You are most welcome, @Conanap. I am glad that the latest PR merge resolved your issue. Version 1.0.4 has also been published to the official npm repository.
