### ISSUE TITLE
KeyError: 'motd_2' , when "-" in the IP

### ISSUE THREAD

**Issue by molanp** [FragLand/minestat#137]
### Expected Behavior
* Output server information

### Actual Behavior/Symptoms
* KeyError: 'motd_2'

### How to Reproduce Behavior/Symptoms
* When  the '-' in IP
* eg: mc-kkk.top:19132

### MineStat Version
* 2.4.1

### Programming Language and Compiler/Interpreter Version
* python 3.9.10

### Operating System
* windows server 2019

### Output/Screenshot(s)
![image](https://user-images.githubusercontent.com/104612722/212217080-73a6fd4d-4ee3-4ceb-aa8a-e85693576a4a.png)
![image](https://user-images.githubusercontent.com/104612722/212217093-2e285fb2-55f2-4a33-acbb-68a31c937c61.png)
I got the package by copying the source code (keeping the attribution) and nothing should go wrong with that

**Comment by ldilley** [comment]
Greetings, @molanp.

I just successfully tested using Python versions 3.9.2 and 3.10.4 to connect to an address containing a hyphen ('-'). I tested against a version 1.8 Java server and a version 1.19.50 Bedrock server. See the output below. Is it possible that there is a bug in your custom code?

```
<23:28:58> (~/projects/minestat/Python) [master *?]
[ldilley@winux] :) {2120}$ python3 -V
Python 3.10.4
<23:29:01> (~/projects/minestat/Python) [master *?]
[ldilley@winux] :) {2121}$ python3 example.py
Minecraft server status of test-host.dom on port 19132:
Server is online running version 1.19.50 Bedrock level(MCPE) with 0 out of 10 players.
Message of the day: Dedicated Server
Message of the day without formatting: Dedicated Server
Latency: 0ms
Connected using protocol: BEDROCK_RAKNET
```

```
<23:36:23> (~/projects/minestat/Python) [master *?]
[ldilley@winux] :) {2123}$ python3 -V
Python 3.9.2
<23:36:54> (~/projects/minestat/Python) [master *?]
[ldilley@winux] :) {2124}$ python3 example.py
Minecraft server status of test-host.dom on port 25565:
Server is online running version 1.8 with 0 out of 20 players.
Message of the day: A Minecraft Server
Message of the day without formatting: A Minecraft Server
Latency: 0ms
Connected using protocol: JSON
```

**Comment by molanp** [comment]
The source code of the package was copied last night (1/12 21:31UTC+8), just now I tested it again, and the output is as follows
![image](https://user-images.githubusercontent.com/104612722/212241493-c85ee5fd-c6b8-4694-95a5-e92dcea844ba.png)
There are two more lines of code than the original package because I declared the source at the beginning of the file

**Comment by molanp** [comment]
Is the version of this server bedrock_server0.14 too old?😂

**Comment by ldilley** [comment]
It looks like this server does not send a secondary MotD or a game mode. If I refrain from reading those fields, I get an acceptable response per the output below. I'll submit a fix tomorrow that validates whether or not those fields are populated prior to reading them. This symptom may also be present in the other language implementations. As a result, these may require a fix as well. Thank you for raising this issue, @molanp.

Raw response:
```
MCPE;§6生存斧§4服§2务§1器  §5QQ群625015871;70;0.14;23;24
```

Typically, we would see something like below (note all the additional fields). Unique server ID, secondary MotD, game mode, numeric game mode, IPv4 port number, and IPv6 port number must have been added later.
```
MCPE;Dedicated Server;390;1.14.60;0;10;13253860892328930865;Bedrock level;Survival;1;19132;19133;
```

Successful test after omitting the absent fields:
```
Minecraft server status of mc-kkk.top on port 19132:
Server is online running version 0.14 with 23 out of 24 players.
Message of the day: §6生存斧§4服§2务§1器  §5QQ群625015871
Message of the day without formatting: 生存斧服务器  QQ群625015871
Latency: 1ms
Connected using protocol: BEDROCK_RAKNET
```

**Comment by molanp** [comment]
Thanks

**Comment by ldilley** [comment]
The PyPI package has been updated to version `2.4.2`, @molanp. Please let me know if that resolved your issue.

**Comment by molanp** [comment]
oh...(Two lines of comments are still added at the beginning of the code)
![image](https://user-images.githubusercontent.com/104612722/212439542-287dbe92-ab0b-410a-8f28-9bf4e112ddaa.png)

**Comment by molanp** [comment]
![image](https://user-images.githubusercontent.com/104612722/212439634-bdd787a9-c431-4aa3-b681-0aad3ea5501f.png)

**Comment by ldilley** [comment]
Hm. The latest Python code from commit 0ba8e04 is working here using the same server now:

```
Minecraft server status of mc-kkk.top on port 19132:
Server is online running version 0.14 (MCPE) with 6 out of 7 players.
Message of the day: §6生存斧§4服§2务§1器  §5QQ群625015871
Message of the day without formatting: 生存斧服务器  QQ群625015871
Latency: 228ms
Connected using protocol: BEDROCK_RAKNET
```

**Comment by molanp** [comment]
OK,now it's up and running

**Comment by molanp** [comment]
Well,there's another issue here, and I don't think it needs to raise another issue.
Everything works fine, but TIMEOUT
![image](https://user-images.githubusercontent.com/104612722/212441397-b8f69d27-7b2c-4438-8e86-e0bd1fac3add.png)

**Comment by ldilley** [comment]
What happens if you modify line 250 to the following?

```python
250     if self.online:
251       self.connection_status = ConnStatus.SUCCESS
252     else:
253       self.connection_status = result
```

**Comment by molanp** [comment]
It`s OK
```
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from data_source import *
>>> ms=MineStat('w1024jk.asia',30080)
>>> ms.version
'1.19.2'
>>> ms.motd
'{"text": "SiTanCraft Server"}'
>>> ms.slp_protocol
<SlpProtocols.JSON: 3>
>>> ms.connection_status
<ConnStatus.SUCCESS: 0>
>>>
```
