### ISSUE TITLE
Is there a Gradle version for java?

### ISSUE THREAD

**Issue by Enderman-Teleporting** [FragLand/minestat#177]
As is asked above. Plz tell me if there is.

**Comment by mindsolve** [comment]
Hi @Enderman-Teleporting,

The package is published to maven central, so you can easily use it in your own gradle projects as dependency.
See for example the different "Gradle" tabs here on how to do it: https://mvnrepository.com/artifact/io.github.fragland/MineStat/3.0.5

Best regards,
MindSolve

**Comment by Enderman-Teleporting** [comment]
Thanks a lot.😁
