### ISSUE TITLE
A question about Java and bedrock server protocols

### ISSUE THREAD

**Issue by molanp** [FragLand/minestat#178]
It seems that in the geyser server, when the java server (TCP) and the bedrock server (UDP) use the same port, it is not possible to specify the protocol to query (Java or Bedrock).

This results in sometimes querying bedrock server results and sometimes querying Java server results.

### Feature Description

* It is desirable to specify whether the server to be queried is Java or bedrock

> If it can be achieved, thank you very much

**Comment by mindsolve** [comment]
Dear @molanp, welcome to MineStat :)

In most of the language variants of minestat you can already choose the protocol to use for communication with the Minecraft server. Since Bedrock/MCPE only uses only one specific network protocol, you can simply set that.

How exactly that works depends on which variant of MineStat you are using.
For example in Python you can use the parameter `query_protocol`, in the Java variant `requestType` and similar in other variants.

For explicitly saying "only Java server" there isn't currently any way that I can think of. If you need that/would like to have that, we can track that as a new feature request.

Best regards,
MindSolve

**Comment by molanp** [comment]
Bedrock servers are not always `BEDROCK_RAKNET` query_protocol, and it may be `EXTENDED_LEGACY` (e.g. 2b2t.xin) or something else, and the `query_protocol` of Java servers is not always `JSON`, and it seems impossible to identify the server type through a limited number of protocols

**Comment by molanp** [comment]
Oh.Is the `slp_protocol` obtained by the query the same as the `query_protocol` in the request parameters, and the above are `slp_protocol` results

**Comment by ldilley** [comment]
Is there a specific language for which you are observing this behavior, @molanp? I just successfully tested Geyser (listening on TCP 25565 and UDP 25565) using the Java implementation of MineStat. In this case, the default behavior checks for TCP communication first if port 19132 is not specified. If you want the Bedrock server results, simply specify Bedrock as the protocol to use. See examples below.

TCP (legacy, beta, extended, and JSON SLP) is attempted first:
```java
MineStat ms = new MineStat("minecraft.frag.land");
```

UDP (Bedrock) is used explicitly even while using the default non-Bedrock server port:
```java
MineStat ms = new MineStat("minecraft.frag.land", 25565, MineStat.Request.BEDROCK);
```

**Comment by molanp** [comment]
I only see this parameter in Ruby and PHP, it seems that only these two languages are supported?
![IMG_20230424_223538](https://user-images.githubusercontent.com/104612722/234029329-d4eadb8a-ce53-46c3-b089-dd9b2eb9b331.jpg)

**Comment by mindsolve** [comment]
No, it's just that the parameters sometimes named differently between the versions.

- For C#: parameter `protocol` (https://github.com/FragLand/minestat/blob/master/CSharp/MineStat/MineStat.cs#L160)
    ```csharp
    MineStat ms = new MineStat("minecraft.frag.land", 25565, protocol: SlpProtocol.Bedrock_Raknet);
    ```

- For Go, its the third optional parameter (and the type for bedrock is `REQUEST_BEDROCK`) - though I don't know enough about Go to give you an example :sweat_smile:.

- For Java (as mentioned above by ldilley): parameter `requestType` (https://github.com/FragLand/minestat/blob/master/Java/me/dilley/MineStat.java#L196)
    ```java
    MineStat ms = new MineStat("minecraft.frag.land", 25565, MineStat.Request.BEDROCK);
    ```

- For Javascript its not possible.
- For PHP: parameter `request_type` (https://github.com/FragLand/minestat/blob/master/PHP/minestat.php#L79)
    ```php
    $ms = new MineStat("minecraft.frag.land", 19132, 5, MineStat::REQUEST_BEDROCK);
    ```
- For Perl: parameter no. 4 set to `REQUEST_BEDROCK`
    ```perl
    $ms = Minecraft::ServerStatus::init("minecraft.frag.land", 25565, Minecraft::ServerStatus::REQUEST_BEDROCK);
    ```
- For PowerShell: parameter `$queryprotocol` (https://github.com/FragLand/minestat/blob/master/PowerShell/MineStat/MineStat.psm1#L126)
- For Python: parameter `query_protocol` (which you can also find in the documentation: https://github.com/FragLand/minestat/tree/master/Python#available-parameters)
    ```python
    import minestat
    ms = minestat.MineStat('minecraft.frag.land', 25565, query_protocol=minestat.SlpProtocols.BEDROCK_RAKNET)
    ```
- For ruby I think you found it yourself (I don't know enough about that language to help you there).

I hope this has cleared up your question :smiley:!

**Comment by molanp** [comment]
oh.THANKS!i found it.
