### ISSUE TITLE
Python: Port from SRV record is not used

### ISSUE THREAD

**Issue by 4310V343k** [FragLand/minestat#183]
### Expected Behavior
* Both address and port are used from the SRV query

### Actual Behavior/Symptoms
* Only the address is used from the SRV query

### How to Reproduce Behavior/Symptoms
* Run Java Edition on port that is different from 25565
* Make an SRV record to point to that port
* Try to query the server by that SRV record `ms = minestat.MineStat("example.com", resolve_srv=True)`
* `print(ms.port)` is the default tcp port

### MineStat Version
* `2.6.1`

### Programming Language and Compiler/Interpreter Version
* Python

### Operating System
* Windows

### Output/Screenshot(s)
```py
srv = dns.resolver.resolve("_minecraft._tcp.example.com", "SRV")[0]
ms = minestat.MineStat("example.com", resolve_srv=True)
```
```
(venv) [03:39:06] $ python main.py
srv.port = 17648, srv.target = <DNS name example.com.>
ms.srv_record = False, ms.address = 'example.com', ms.port = 25565
```

**Comment by mindsolve** [comment]
Hi @4310V343k,

A warm welcome to MineStat, and thanks for reporting this issue!

I've been able to reproduce the problem. It lies within the fact that we accidentally resolve the SRV record two times, and change the queried hostname during the protocol autodetection, so between the different SRV resolutions.

A quick fix that disables the second SRV resolution if valid data was retrieved the first time will be included soon.
A logic change that completely removes the need for double SRV resolution for any other case will be created as soon as time permits (soon :tm:) - though that doesn't impact this issue :)

Best regards,
MindSolve
