### ISSUE TITLE
Powershell -> PHP

### ISSUE THREAD

**Issue by Deadlineem** [FragLand/minestat#193]
### Feature Description
Powershell to PHP

I've created a script to run the powershell command for MineStat in PHP.  Install minestat through powershell and then run this on your webserver (if locally hosted) this can probably be mocked up a bit more to allow multiple-ports/protocols but it does pull status from multiple hosts as long as said hosts are running the same type of server (Java + Java) or (Bedrock + Bedrock) possibly (Java+Geyser/Floodgate as well)

```
<?php
//Host information
$serverIP = array("localhost"); // The IP/Hostname of the server you want to get data from, its in an Array value for multiple hosts
$serverIP = implode(',', $serverIP);
$port = "19132"; // Port for the server to listen on, bedrock is 19132 by default, Java is 25565

// Valid Protocols: Unknown, Beta, Legacy, ExtendedLegacy, Json, BedrockRaknet
// Use BedrockRakNet for Bedrock/Pocket Edition, The rest will not work with bedrock servers.  Also, BedrockRaknet does not output player usernames.
$protocol = "BedrockRaknet";


$runCMD = "MineStat -Address ".$serverIP." -Port ".$port." -Protocol ".$protocol." -Timeout 1 ";
$output = shell_exec('powershell.exe '.$runCMD);

echo "<pre>".$output."</pre>";
?>
```

Output for 1 Host (localhost)
https://imgur.com/kCokMuq

Output for Multiple Hosts (localhost and play.minefort.com)
https://imgur.com/L4ItSF1

**Comment by ldilley** [comment]
Greetings, @Deadlineem. Is this something that you want to contribute to the project? I am fine with creating a `contrib` directory for scripts like this. Feel free to submit a pull request (PR) to include your contribution. Here is a guide for submitting PRs if you are not familiar with the process: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by Deadlineem** [comment]
Hey @ldilley I actually just put this up on my github, sort of "extending" it off of MineStat.  I dubbed the project "Multi-Stat"

https://github.com/Deadlineem/Multi-Stat

You can add this to Minestat's main repo under a contrib directory if you'd like :)

**Comment by ldilley** [comment]
Thank you. I will close this issue since you submitted PR #196.
