### ISSUE TITLE
Player Username option

### ISSUE THREAD

**Issue by Deadlineem** [FragLand/minestat#194]
### Feature Description
I was looking up on Bedrock Protocols, I noticed there was information about usernames
https://wiki.vg/Bedrock_Protocol#Add_Player

0x0C is for the usernames, not sure if its possible to query them or not, but i would love to be able to get the xuid and username of the players who are on the server currently.

Im not sure how any of this works, but is it possible to put this into MineStat?  Possibly have it as an optional?

-showUsernames (-sU) true/false (default to false if not set)

Example: `Powershell -> MineStat -Address localhost -Port 19132 -Protocol BedrockRaknet -sU true -Timeout 1 `

**Comment by Deadlineem** [comment]
@ldilley I forgot to mention, the playerlist option works if you change it in the minestat powershell file, however, it ONLY works on Java, not bedrock.  Hopefully the link helps getting the bedrock player list, im hopeful for that lol.

**Comment by ldilley** [comment]
MineStat is using RakNet unconnected ping for communication and the pong response does not contain player information. See here for details: https://wiki.vg/Raknet_Protocol#Unconnected_Ping

The protocol you linked is for game client <-> Bedrock server communication. The GameSpy4/Unreal Tournament 3 query protocol can return player information if using a full stat request (https://wiki.vg/Query#Full_stat). The PowerShell, Python, and Ruby implementations of MineStat support this. Many servers do not have the query port open however. Lastly, SLP 1.7 (JSON) responses may also contain player information. See the "sample" array in the example output at https://wiki.vg/Server_List_Ping#Status_Response. This field is dependent on the server software and configuration I believe. As a result, not all SLP 1.7 responses will have these details.

**Comment by Deadlineem** [comment]
So, the bedrock dedicated servers dont support player name queries currently then?  I did notice i can retrieve playerList from Java/Spigot/Geyser servers easily.  Its the bedrock server i'd like.  I have a website i want to port player data to (stats and name/xuid) for people to track their stats and earn rewards for progress in the world.

**Comment by ldilley** [comment]
That is correct. This information can likely be obtained from the server console, the server logs, or the server data files.

**Comment by Deadlineem** [comment]
@ldilley Any idea where or how i could modify or read the data from the server data files?  I am assuming its located either inside the .pdb or the worlds/<World Name>/db files of the server.  I just dont have any idea how to view/edit them or the data they contain.  If i can figure that out, i can progress much farther.

I can read from the server log files, however, the log files are only updated after the server is shut down, when its running, it does not contain information in the log file.

Any idea how i would pull live data from the console?  Thats a possibility as well.  I appreciate your help!

**Comment by ldilley** [comment]
I am not certain, but you could try periodically extracting the output of the `list` command. This is also beyond the scope of MineStat.

**Comment by ldilley** [comment]
Closing issue since the original inquiry was answered.
