### ISSUE TITLE
Possible runtime error when MotD is empty/null

### ISSUE THREAD

**Issue by ldilley** [FragLand/minestat#203]
*Note:* This issue was submitted due to @molanp closing #200 prematurely. #200 is also Python specific. This issue covers all supported languages.

### Tracker
|Language|Affected?|Fixed?|
|-|-|-|
|**C#**|:x:|N/A|
|**Go**|:x:|N/A|
|**Java**|:heavy_check_mark:|:heavy_check_mark: v3.0.6 (PR #204)|
|**JavaScript**|:x:|N/A|
|**Perl**|:x:|N/A|
|**PHP**|:x:|N/A|
|**PowerShell**|:x:|N/A|
|**Python**|:heavy_check_mark:|:heavy_check_mark: v2.6.2 (PR #201)|
|**Ruby**|:heavy_check_mark:|:heavy_check_mark: v3.0.3 (PR #202)|

### Expected Behavior
* If the MotD value obtained from a server is empty, the field should be empty.

### Actual Behavior/Symptoms
* Some language implementations of MineStat do not handle empty/null MotDs and produce an error message instead.

### How to Reproduce Behavior/Symptoms
* Attempt to query a Minecraft server using an SLP 1.7 (JSON) request while the server is set with an empty MotD (`server.properties` contains `motd=`).

### MineStat Version
* Potentially all

### Programming Language and Compiler/Interpreter Version
* Potentially all

### Operating System
* Any

### Output/Screenshot(s)
N/A

**Comment by molanp** [comment]
In PHP, `description` is NULL, but it doesn't seem to affect its concatenation with the string.

**Comment by ldilley** [comment]
This issue has been resolved for each affected implementation.
