### ISSUE TITLE
Add >=1.7 ping support

### ISSUE THREAD

**Issue by ldilley** [FragLand/minestat#21]
#20 was created to add 1.6 SLP support. To become current, 1.7 should also be implemented. The handshake for 1.7 should be as follows:

```
1. Send 0x00 (handshake packet) with the following fields:
  1a. integer indicating protocol version (just send 1 for ping)
  1b. remote server address as a string
  1c. remote server port as an unsigned short
  1d. send integer 1 to request server status
2. Send 0x00 (request packet)
3. Server should respond with 0x00 and JSON data that must be parsed.
```

**Comment by lUNuXl** [comment]
Hello,

I've run into issues integrating this library into my project and only after a few hours of debugging I checked issues in this repository.

Please add README.md with a list of supported versions. The version I've run into problems with is 1.19.2 (Paper).

Thanks

**Comment by ldilley** [comment]
Please see the table in issue #43. SLP 1.7 (JSON) requests should be able to query 1.19.x servers. What programming language are you using, @lUNuXl?

**Comment by lUNuXl** [comment]
Thank you for quicky reply, I'm using java 17.

The snippet of code that always reports that server is down:

```
            log.info("Checking server status: {}:{}", ip, MINECRAFT_PORT);
            MineStat mineStat = new MineStat(ip, MINECRAFT_PORT);

            int players;
            if(mineStat.isServerUp()) {
                log.info("Server {} {} is up", instance.getName(), ip);
                players = mineStat.getCurrentPlayers();
            } else {
                log.info("Server {} {} is down", instance.getName(), ip);
                players = 0;
            }

            log.info("Players online: {}", players);
            ```

**Comment by ldilley** [comment]
For protocol support status, please see issue #43.
