### ISSUE TITLE
Requesting rubygems.org co-ownership access

### ISSUE THREAD

**Issue by ldilley** [FragLand/minestat#24]
I hope you are still around, @unn4m3d. I recently created an account on rubygems.org to update the [minestat](https://rubygems.org/gems/minestat) Ruby gem. You are currently the only owner, so I do not have access unfortunately. Would it be possible to add me at your convenience please? I've also sent you an e-mail as another means of contacting you. My rubygems.org username is LDilley. Here are the instructions to add a gem co-owner: https://guides.rubygems.org/command-reference/#gem-owner

Thank you for any assistance that you can provide, sir.

**Comment by ldilley** [comment]
I've submitted an inquiry to the RubyGems.org Support Team to see about getting added as a co-owner of this gem since I have not been able to contact the current maintainer via e-mail or on GitHub.

**Comment by FluorescentGreen5** [comment]
Is there any sort of security risk to using the outdated gem?

**Comment by ldilley** [comment]
There is no security risk to my knowledge, @FluorescentGreen5.

**Comment by ldilley** [comment]
Approving gem ownership addition of self by request of @sonalkr132 from the RubyGems Support Team.

**Comment by sonalkr132** [comment]
Please make sure following says `owner`:
![Screenshot from 2020-04-21 10-57-05](https://user-images.githubusercontent.com/7680662/79828788-1145ca00-83bf-11ea-8059-200434c6d0f5.png)

we need this:
![Screenshot from 2020-04-21 09-34-20](https://user-images.githubusercontent.com/7680662/79828734-fa06dc80-83be-11ea-8b07-2f3bdee5b44f.png)

**Comment by ldilley** [comment]
Greetings, @sonalkr132.

Within GitHub organizations (`Frag Land` in this context), the "Owner" role is not publicly reflected in issue comments despite the commenter being the owner of the organization. If this repository was not under an organization and instead was under an individual, they would appear as "Owner" in issue comments.

Here is a screenshot showing that I am the owner of the organization which the MineStat repo is a part of:
![repo_owner_screenshot](https://user-images.githubusercontent.com/3323717/80042901-3d9c3c00-84ce-11ea-8d27-c5dbf79a694a.png)

To ensure I was not missing something, I created a support case with GitHub (reference ID #655896). This is what they had to say:

```
Ben (GitHub Support)

Apr 22, 7:16 PM UTC

Hey Lloyd,

Thanks for reaching out!

For this repository – https://github.com/FragLand/minestat – the "owner" is technically the FragLand organization, as opposed to your personal ldilley user account.

That's why when you look at the other example – https://github.com/ldilley/rubircd/ – you're listed as the "owner" because the repository was created directly by your ldilley user account.

I hope this helps to clear up the discrepancy, and please let us know if you have any other questions.

Best regards,
Ben
```

If you have further doubts, you can also see that I made the very first commit for this project on 4/18/2014 here: https://github.com/FragLand/minestat/commit/2ec5378a7c7320694c57a6959c68220fe6961826

Please let me know if you require anything else.

**Comment by sonalkr132** [comment]
Oh, my bad. I never noticed this. Thank you for checking with GitHub support. I will add on you on Saturday. Ping me on the ticket, in case I forget.

**Comment by ldilley** [comment]
Thank you very much for resolving this issue, @sonalkr132. I have validated RubyGems access.
