### ISSUE TITLE
motd issue in python (fixed the bug)

### ISSUE THREAD

**Issue by Nortank12** [FragLand/minestat#28]
I used it in python and my app stopped working because of a type error:
TypeError: a bytes-like object is required, not 'str'

But I found the bug:
# Parse the received data
    if raw_data is None or raw_data == '':
      self.online = False
    else:
      data = raw_data.decode('cp437').split('\x00\x00\x00')
      if data and len(data) >= self.NUM_FIELDS:
        self.online = True
        self.version = data[2].replace("\x00", "")
        self.motd = data[3].encode('utf-8').replace("\x00", "")  #HERE!!
        self.current_players = data[4].replace("\x00", "")
        self.max_players = data[5].replace("\x00", "")
      else:
        self.online = False

I just had to swap them so it firstly replaces the "\x00" to "" than encodes it to utf-8, it fixed my issue.
# Parse the received data
    if raw_data is None or raw_data == '':
      self.online = False
    else:
      data = raw_data.decode('cp437').split('\x00\x00\x00')
      if data and len(data) >= self.NUM_FIELDS:
        self.online = True
        self.version = data[2].replace("\x00", "")
        self.motd = data[3].replace("\x00", "").encode('utf-8')
        self.current_players = data[4].replace("\x00", "")
        self.max_players = data[5].replace("\x00", "")
      else:
        self.online = False

**Comment by ldilley** [comment]
Thank you for the report, @Nortank12. Apologies for the delay as well -- I recently returned from a trip. I am not able to replicate this symptom. Out of curiosity, what version of Python and what operating system are you using?

As a side note, the Python implementation will be rewritten to accommodate #20, #21, and #22. It will ideally be a port of the current Ruby implementation: https://github.com/ldilley/minestat/blob/master/Ruby/lib/minestat.rb. The Python rewrite should prevent this symptom from manifesting. I'll leave this issue open for tracking purposes until the new code can be tested by you.

**Comment by Nortank12** [comment]
Thank you for your answer, @ldilley. I use Windows 10 and Python 3.6.6.

**Comment by elJoa** [comment]
I can replicate this issue in Windows 10, Python 3.8.3.

**Comment by ldilley** [comment]
Fixed in e12febe.
