### ISSUE TITLE
current_players when convert bug

### ISSUE THREAD

**Issue by matahombres** [FragLand/minestat#31]
### Expected behavior
When convert integer number get all number
### Actual behavior/symptoms
When convert integer only one numer. Ej -> String(18) -> int(1)
### Steps to reproduce behavior/symptoms
Get current_players and put intval($current_players)
### MineStat version
May 25, 2019 
### Programming language and compiler/interpreter version
PHP apache
### Operating system
Ubuntu 18.4

The problem is the have one "invisible" character in middle the numbers.
For the posible solution i was thinking about a character path and then check if they are numbers

**Comment by ldilley** [comment]
Greetings, @matahombres.

I apologize for the delay in responding and appreciate your report. I have been busy with some server migrations for the past couple of months and have not had an opportunity to log into GitHub for a while. My development system was also impacted by the aforementioned migrations. As a result, I'll require some more time to get my development environment back together (install PHP, etc.) to test this. In the interim, you could sanitize `$current_players` prior to int conversion as a workaround.

**Comment by ldilley** [comment]
This issue has been resolved.
