### ISSUE TITLE
Server keeps printing out "Server is Offline", worked before.

### ISSUE THREAD

**Issue by ItsVinnyX** [FragLand/minestat#37]
### Expected behavior
Should be showing the number of players online.

### Actual behavior/symptoms
It is showing "Server is Offline!"

### Steps to reproduce behavior/symptoms
Not sure.

### MineStat version
Latest.

### Programming language and compiler/interpreter version
Java, Eclipse IDE

### Operating system
Centos 7

`package com.venomsurge;

import com.venomsurge.handlers.CommandHandler;
import com.venomsurge.listeners.CommandListener;
import com.venomsurge.listeners.MyListener;
import com.venomsurge.minecraft.MineStatus;
import com.venomsurge.music.commands.MusicCommand;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.OnlineStatus;
import net.dv8tion.jda.api.entities.Activity;

public class VenomBOT implements Runnable {

	public static JDA api;

	public void run() {
		while (true) {
			String server = "";
			MineStatus ms = new MineStatus("play.venomsurge.net", 25565);
			if (ms.isServerUp()) {
				if (Integer.parseInt(ms.getCurrentPlayers()) == 1) {
					server = "VenomSurge with 1 player.";
				} else {
					server = "VenomSurge with " + ms.getCurrentPlayers() + " players.";
				}
			} else {
				server = "Server is offline!";
			}
			api.getPresence().setActivity(Activity.playing(server));
			try {
				Thread.sleep(30000);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
	}

	public static void main(String[] args) throws Exception {
		String server = "";
		MineStatus ms = new MineStatus("play.venomsurge.net", 25565);
		if (ms.isServerUp()) {
			if (Integer.parseInt(ms.getCurrentPlayers()) == 1) {
				server = "VenomSurge with 1 player.";
			} else {
				server = "VenomSurge with " + ms.getCurrentPlayers() + " players.";
			}
		} else {
			server = "Server is offline!";
		}
		// Initialize the bot status
		api = JDABuilder.createDefault("MY KEY").setStatus(OnlineStatus.ONLINE).setActivity(Activity.playing(server))addEventListeners(new MyListener(), new CommandListener()).build();
		CommandHandler.commands.put("m", new MusicCommand());
		CommandHandler.commands.put("music", new MusicCommand());
		// Launch thread to periodically update the status
		new Thread(new VenomBOT()).start();

	}
}`

**Comment by ldilley** [comment]
This is related to #19. Your server does not respond to legacy queries. I used the updated Ruby version of MineStat which implements the protocols for 1.4/1.5 along with 1.6 and I am able to query your server fine. Below are the results. The Java version of MineStat requires #20 be implemented or, at least, support for 1.4/1.5 added before it can talk to your newer software.

As for an ETA: I admittedly do not have one as I've been allocating time toward other necessities and interests. I fixed the Ruby version a while back and was hoping that other potential contributors could use that as a guide for the other language implementations. If I get some motivation, I'll try to prioritize the Java version next.

```console
[ldilley@devm] :) {3742}$ ruby example.rb
Minecraft server status of play.venomsurge.net on port 25565:
Server is online running version VinnyCord 1.7.x-1.15.x with 8 out of 60 players.
Message of the day: §f§a§lVENOM§f§lSURGE §8➠ §e§lSEARCH AND DESTROY §7§l-§8§l §8(§71.9+§8)
Latency: 115ms
```

**Comment by ItsVinnyX** [comment]
I understand, if you could that’d be great because my whole Discord Bot runs on this haha.

**Comment by ldilley** [comment]
I've ported the new Ruby code to Java just for you, @ItsVinnyX. I tested the latest commit, caedbe6, against your server and I am now able to query it. Please test when able and let me know.

**Comment by ldilley** [comment]
Have you had any time to test yet, @ItsVinnyX? If I don't see a response within the next 3 days, I'll assume this is resolved and close the issue.

**Comment by ItsVinnyX** [comment]
Works! Thanks again.
