### ISSUE TITLE
Using multiple servers in one function

### ISSUE THREAD

**Issue by Yuki-KobayashiJP** [FragLand/minestat#47]
Hey Dilley,

 I started creating API with your js, and I want to have multiple servers in one function.

### Example of API output.
{seperated_count:{"Skyblock":[355, 55], "Hubs":[588, 0, 45]}, "server_total": 1043}

I'm using nodeJS for the API. I cannot figure out how to put multiple servers in one function.
I tried everything but I didn't get any solution for it.

Woud you please help me with that?

I can figure everything about designing it and that stuff my self ofc, I just need you help with puttin multiple servers in the function.

Thank you for any kind of answer.

With regards,
 Yuki Kobayashi.

**Comment by ldilley** [comment]
Greetings, @Yuki-KobayashiJP.

I would handle this by creating a wrapper function that accepts an array of addresses. You could then query each address in a synchronous or asynchronous manner (depending on your preference) and wait for the results. If you also want to include the port number, define a JSON object capable of housing both the address and port. Then, pass an array containing multiple objects to your wrapper function. For example:

```js
const mcservers = [
  {
    address: 'address1.somedomain',
    port: 25567
  },
  {
    address: 'address2.anotherdomain',
    port: 25568
  }
]

function yuki_wrapper(arr)
{
  for(mchost in arr)
  {
    let ms = require('./minestat');
    ms.init(mchost.address, mchost.port, function(result)
    {
      // do something with result
    });
  }
}

yuki_wrapper(mcservers)
```

I hope that you find the above advice helpful.

**Comment by Yuki-KobayashiJP** [comment]
Thank you! You're a saviour.

Hope you have a great day, again thanks for the help.

**Comment by Yuki-KobayashiJP** [comment]
Ok,
I've tried the option with port number, I've got no errors so far, but after I used console.log to write result I've got undefined.
I cannot figure out where is the problem because even when I defined err function I've got no error. Any idea what is happening?
![image](https://user-images.githubusercontent.com/57325593/101232016-6a910e00-36af-11eb-950a-f1b2019b057d.png)

**Comment by ldilley** [comment]
Apologies; try the code below instead.

```js
function yuki_wrapper(arr)
{
  for(s in arr)
  {
    let ms = require('./minestat');
    ms.init(arr[s].address, arr[s].port, function(result)
    {
      // do something with result
    });
  }
}
```

**Comment by Yuki-KobayashiJP** [comment]
Ok it worked only for the first server the second didn't even got detected.

**Comment by ldilley** [comment]
The second host not responding may be due to issues #20, #21, and/or #22. See issue #43 for a table of protocol support. The JavaScript implementation of MineStat is missing support for several versions of the SLP (Server List Ping) protocol.

**Comment by Yuki-KobayashiJP** [comment]
Is there a way to fix that problem? Or is it better to go to PHP that supports all versions?

**Comment by ldilley** [comment]
Yes; it requires adding support for the missing SLP protocol versions to the JavaScript implementation. I've done that for PHP, Ruby, and mostly Java. I anticipate getting around to the other languages some day, but I do not have an ETA unfortunately.

If you are comfortable with PHP, you could certainly try that route.

**Comment by Yuki-KobayashiJP** [comment]
I see, I've got it fixxed with using only my servers but I've got in the point where I've got error code: 'ERR_HTTP_HEADERS_SENT'
I've searched for some fixes on this one but none work.

Sending cut of my code again if you could help. 

![image](https://user-images.githubusercontent.com/57325593/101234842-37f11080-36c3-11eb-98da-9cefa5d27060.png)

**Comment by ldilley** [comment]
`ms.current_players` is correct. However, this is not a service that speaks HTTP nor is the result in JSON format. You could store the data in a JSON object if you desired though. I am not sure how you want to present/store the data. This is really up to you. Valid data consists of:

| Field | Purpose |
|-------|----------|
`ms.address` | Remote Minecraft server address |
`ms.port` | Remote Minecraft server port
`ms.latency` | Latency in milliseconds to communicate with remote Minecraft server |
`ms.online` | Boolean value to indicate whether or not remote Minecraft server is online |
`ms.current_players` | Current players on Minecraft server |
`ms.max_players` | Configured maximum players on Minecraft server |
`ms.motd` | Minecraft server message of the day |
`ms.version` | Remote Minecraft server version |

**Comment by ldilley** [comment]
Does the example below help? The function returns an array of JSON data. The caller can parse and display the data however they want.

```js
function yuki_wrapper(arr)
{
  var json_data = [];
  var json_obj = {};
  for(var s in arr)
  {
    let ms = require('./minestat');
    ms.init(arr[s].address, arr[s].port, function(result)
    {
      if(ms.online)
      {
        json_obj = {
          current_players: ms.current_players,
          max_players: ms.max_players,
          motd: ms.motd,
          version: ms.version,
          address: ms.address,
          port: ms.port,
          online: ms.online,
          latency: ms.latency
        }
      }
      else
      {
        json_obj = {
          current_players: 0,
          max_players: 0,
          motd: 'null',
          version: 'null',
          address: ms.address,
          port: ms.port,
          online: false,
          latency: -1
        }
      }
      json_data.push(json_obj)
    });
  }
  return json_data
}
```

**Comment by ldilley** [comment]
Closed due to lack of response.
