### ISSUE TITLE
Python 

### ISSUE THREAD

**Issue by Lzyen** [FragLand/minestat#51]
Python Module Name?
How to use python script

**Comment by ldilley** [comment]
@Lzyen: The module name is `minestat` and there is a usage example in the project [README.md](https://github.com/FragLand/minestat/blob/master/docs/README.md). I've included it below.

```python
import minestat

ms = minestat.MineStat('minecraft.frag.land', 25565)
print('Minecraft server status of %s on port %d:' % (ms.address, ms.port))
if ms.online:
  print('Server is online running version %s with %s out of %s players.' % (ms.version, ms.current_players, ms.max_players))
  print('Message of the day: %s' % ms.motd)
  print('Latency: %sms' % ms.latency)
else:
  print('Server is offline!')
```

**Comment by ldilley** [comment]
You may also now install MineStat as a Python package via: `pip install minestat`

I will consider your issue resolved if there is no reply within 7 days.

**Comment by Lzyen** [comment]
Resolved!
