### ISSUE TITLE
question / bug python 

### ISSUE THREAD

**Issue by Jcodeerd** [FragLand/minestat#54]
### Expected behavior
show the latency, motd, player amount

### Actual behavior/symptoms

AttributeError: module 'minestat' has no attribute 'MineStat'

### Steps to reproduce behavior/symptoms

1. go to your python version
2. go to `site-packages` folder
3. make a minestat.py and put the https://github.com/FragLand/minestat/blob/master/Python/minestat.py code in.
4. use the example
5. get the error

### MineStat version
idk, this one: https://github.com/FragLand/minestat/blob/master/Python/minestat.py

### Programming language and compiler/interpreter version
python (3.8.7)
VScode 
![image](https://user-images.githubusercontent.com/68161666/108346098-4ee1d200-71df-11eb-9d7b-a27773409696.png)

### Operating system

Windows 10 (20H2, build: 19042.804, experience: Windows Feature Experience Pack 120.2212.551.0)

Am I just doing something dumb?

**Comment by ldilley** [comment]
Hello, @Jcodeerd.

I suspect that your symptom pertains to an issue with the module not being in your Python path. To validate the paths that your Python interpreter looks for modules in, run the following:
```python
import sys
sys.path
```

The output should look similar to the following:
```python
['', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages']
```

Ensure that `minestat.py` resides in one of the directories included in your `sys.path`. You can also now install MineStat as a Python package with: `pip install minestat`

**Comment by Jcodeerd** [comment]
![image](https://user-images.githubusercontent.com/68161666/108477001-f966fd00-7292-11eb-96cb-d3bbf5c6fbb9.png)
I put the file in the path I marked tho.

**Comment by ldilley** [comment]
And the same error message occurs after installing the module via `pip`? Are you able to provide a screenshot showing the contents of `C:\\Users\\Familie PC\\AppData\\Roaming\\Python\\Python38\\site-packages`? I just performed a fresh install of the latest Python interpreter for Windows (3.9.2) along with the `minestat` module. I am not experiencing the issue that you are reporting. I've included the contents of my `site-packages` directory as well for comparison purposes.

```cmd
C:\Users\ldilley>pip install minestat
Collecting minestat
  Downloading minestat-1.0.1-py3-none-any.whl (15 kB)
Installing collected packages: minestat
Successfully installed minestat-1.0.1
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'c:\users\ldilley\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

C:\Users\ldilley>python
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import minestat
>>> ms = minestat.MineStat('minecraft.frag.land', 25565)
>>> import sys
>>> sys.path
['', 'C:\\Users\\ldilley\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip', 'C:\\Users\\ldilley\\AppData\\Local\\Programs\\Python\\Python39\\DLLs', 'C:\\Users\\ldilley\\AppData\\Local\\Programs\\Python\\Python39\\lib', 'C:\\Users\\ldilley\\AppData\\Local\\Programs\\Python\\Python39', 'C:\\Users\\ldilley\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages']
```

![image](https://user-images.githubusercontent.com/3323717/108601271-d22f2f00-7369-11eb-9cf2-3c85b6000e49.png)

**Comment by Jcodeerd** [comment]
Well, with the Pypi package it works, thanks!
