### ISSUE TITLE
Publish Java package to Maven Central Repository

### ISSUE THREAD

**Issue by grimsi** [FragLand/minestat#82]
First of all, you did and still do a great job maintaining this project!

I would really like to have an official package published to Maven Central, so that using this library in your application becomes as easy as adding the dependency to your build file.

This should be an easy win in theory, since no new code has to be written.
Here is an overview of what's necessary in order to tackle this: https://maven.apache.org/repository/guide-central-repository-upload.html

**Comment by ldilley** [comment]
The requested components were published to Maven Central and are available at: https://search.maven.org/search?q=a:MineStat
