### ISSUE TITLE
Version/MOTD and Bungeecord/Waterfall problems.

### ISSUE THREAD

**Issue by Osiris-Team** [FragLand/minestat#87]
Hey, I'm the dude from this pull request: https://github.com/FragLand/minestat/pull/86
Minestat doesn't detect the versions properly.
See https://autoplug.online/servers and navigate to "new" to see what I mean. (I get this for all servers: >=1.8b/1.3)
When using newer request methods first (like in the PR), I don't get this problem and I'm able to retrieve the right versions, BUT retrieving the MOTD fails and waterfall/bungecoord servers get spammed like one of my users reported here: https://discord.com/channels/707539055448948808/709179613540122744/878806086927400971
Tell me if you need more info, I'm more than happy to provide it ^^

### MineStat Version
2.0.0

### Programming Language and Compiler/Interpreter Version
Java

### Operating System
Windows 10 (latest)

**Comment by mindsolve** [comment]
Dear Osiris-Team,

I can replicate the described behaviour (failing version detection) with the Java version of minestat against a Bungeecord/Waterfall Minecraft proxy.
The python version doesn't seem to be affected, as I could not replicate the behaviour there.
The issue with the java version might take a little to actually debug, sorry for that.

The problem with missing MOTD is related to issue FragLand/minestat#84, and has to do with the correct parsing of a modern json MOTD with formatting. This is currently in progress.

Best regards,
MindSolve

**Comment by Osiris-Team** [comment]
Any news? Has been almost 10 days.

**Comment by mindsolve** [comment]
Dear @Osiris-Team,

I have opened a new PR (#89) that fixes your problems, including:
- The empty MOTDs
- The wrong version detection
- Log spam on Bungeecord/Waterfall servers

I would appreciate if you could test the changes and report back whether they actually helped.

Best reagards,
~MindSolve
