### ISSUE TITLE
Organisational: Project handover

### ISSUE THREAD

**Issue by mindsolve** [FragLand/minestat#88]
Hello everbody!

The original developer and maintainer of MineStat, the dear @ldilley has informed me, that he is no longer able to maintain MineStat and whishes to step down from his position as maintainer. He offered me take over the project from him, as we both think that MineStat should not simply be archived, but instead get a new maintainer and a litte fresh wind in the sails.

I see the following points as to-dos in this regard:

- [X] @mindsolve: Create new Github organisation `minestat-org` for MineStat
  - Done! https://github.com/minestat-org
- [ ] ~~@ldilley: Move the repository `minestat` there~~
  - *moving the repo keeps all issues, the history and links intact, see https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository#about-repository-transfers*

After this is done, we can talk about how the new repo should be handled, what changes should be done and how to do this together as a community.

Best regards,
~MindSolve

**Comment by Osiris-Team** [comment]
Love it! Lets go make MineStat great again!

**Comment by ldilley** [comment]
After further conversation with @mindsolve via Discord, we've decided to keep the repository under the @FragLand organization and continue development of the project here. We've also enabled [Discussions](https://github.com/FragLand/minestat/discussions) as a replacement for Discord.

I'll keep this issue open for a week from the time of this writing in case @mindsolve has any additional input or in case there is something I've missed.

**Comment by mindsolve** [comment]
I can only agree with @ldilley, a continuation of the project here is the best way forward. Other than that, I have nothing to add - If anybody has any questions or suggestions regarding to changes to the project, feel free to open a new discussion on the link posted above 😃.
