### ISSUE TITLE
Wrong Java logic in requests??

### ISSUE THREAD

**Issue by Osiris-Team** [FragLand/minestat#97]
Beginning at line https://github.com/FragLand/minestat/blob/e37b365c954d283559b1b7db0cf7a5b69161160e/Java/me/dilley/MineStat.java#L163
Shouldn't the logic be this instead: (which would also match more to whats said in the comment above)
```java
        // SLP 1.4/1.5
        Retval retval = legacyRequest(address, port, getTimeout());
        // SLP 1.8b/1.3
        if(retval != Retval.SUCCESS)
          retval = betaRequest(address, port, getTimeout());
        // SLP 1.6
        if(retval != Retval.SUCCESS)
          retval = extendedLegacyRequest(address, port, getTimeout());
        // SLP 1.7
        if(retval != Retval.SUCCESS)
          retval = jsonRequest(address, port, getTimeout())
```
Because if we keep the logic as it is, namely:
```java
        // SLP 1.4/1.5
        Retval retval = legacyRequest(address, port, getTimeout());
        // SLP 1.8b/1.3
        if(retval != Retval.SUCCESS && retval != Retval.CONNFAIL)
          retval = betaRequest(address, port, getTimeout());
        // SLP 1.6
        if(retval != Retval.CONNFAIL)
          retval = extendedLegacyRequest(address, port, getTimeout());
        // SLP 1.7
        if(retval != Retval.CONNFAIL)
          retval = jsonRequest(address, port, getTimeout())
```
Then the other requests are done even though the request before already was successfull.

**Comment by ldilley** [comment]
Greetings, @Osiris-Team.

Are you having an issue receiving a valid response back from servers using the Java implementation? Can you please share the output along with the server address and port if so? The sequence of queries should be correct and matches the Ruby logic (included below). Both the Java and Ruby implementations were also peer reviewed and tested prior to merging. I agree that the preceding comment block is misleading. These comments should be updated to reflect the recent changes to the query behavior. I'll take care of that and respond to this issue when complete.

```ruby
        # SLP 1.4/1.5
        retval = legacy_request()
        # SLP 1.8b/1.3
        unless retval == Retval::SUCCESS || retval == Retval::CONNFAIL
          retval = beta_request()
        end
        # SLP 1.6
        unless retval == Retval::CONNFAIL
          retval = extended_legacy_request()
        end
        # SLP 1.7
        unless retval == Retval::CONNFAIL
          retval = json_request()
        end
    end
```

**Comment by Osiris-Team** [comment]
Yeah, one of my users is having trouble retrieving his server information with MineStat. I am still figuring out the problem and notify you when I got more info on this.

**Comment by ldilley** [comment]
The relevant comments pertaining to stopping on successful connection have been updated. As for **_why_** the sequence matters, have a look at issue #70 along with the following comments from the Python code:

```python
    # Note: The order here is unfortunately important.
    # Some older versions of MC don't accept packets for a few seconds
    # after receiving a not understood packet.
    # An example is MC 1.4: Nothing works directly after a json request.
    # A legacy query alone works fine.
```

**Comment by Osiris-Team** [comment]
I understand why the sequence matters, but I still don't understand why the other requests must be made, since the request before was already succesfful.

**Comment by Osiris-Team** [comment]
Ok I guess the older requests don't contain all the information (like motd) we need, that's why the subsequent requests are done.
